#!/bin/bash
# My first script
a=$(pwd)

file="$a/temp/"
if [ -d "$file" ]
then
	echo "$file found."
	echo "Ingrese Codigo: "
	read input_variable
	find * -name "*$input_variable*" -exec mv {} temp/ \;
else
	echo "No aplica"
fi


 

